Merge remote-tracking branch 'origin/nightly'

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -504,8 +504,9 @@ jobs:
               tag="${{ needs.setup_release.outputs.release_tag }}"
               version="${{ needs.setup_release.outputs.release_version }}"
             else
-              tag="${{ github.ref_name }}"
-              version="0.0.${{ github.run_number }}"
+              matrix=$((
+                echo '{ "arch" : ["x86_64"] }'
+              ) | jq -c .)
             fi
           else
             echo "This is a PR event"
@@ -872,21 +873,147 @@ jobs:
               [string]$Uri,
               [string]$OutFile
             )
-
-            $maxRetries = 5
-            $retryCount = 0
-            $success = $false
-
-            while (-not $success -and $retryCount -lt $maxRetries) {
-              $retryCount++
-              Write-Host "Downloading $Uri to $OutFile, attempt $retryCount of $maxRetries"
-              try {
-                Invoke-WebRequest -Uri $Uri -OutFile $OutFile
-                $success = $true
-              } catch {
-                Write-Host "Attempt $retryCount of $maxRetries failed with error: $($_.Exception.Message). Retrying..."
-                Start-Sleep -Seconds 5
+            if [[ "${{ matrix.os_version }}" == "14" ]]; then
+              # TCC access table in Sonoma has extra 4 columns: pid, pid_version, boot_uuid, last_reminded
+              for i in "${!values[@]}"; do
+                values[$i]="${values[$i]},NULL,NULL,'UNUSED',${values[$i]##*,}"
+              done
+            fi
+  
+            # system and user databases
+            dbPaths=(
+              "/Library/Application Support/com.apple.TCC/TCC.db"
+              "$HOME/Library/Application Support/com.apple.TCC/TCC.db"
+            )
+  
+            for value in "${values[@]}"; do
+              for dbPath in "${dbPaths[@]}"; do
+                echo "Column names for $dbPath"
+                echo "-------------------"
+                sudo sqlite3 "$dbPath" "PRAGMA table_info(access);"
+                echo "Current permissions for $dbPath"
+                echo "-------------------"
+                sudo sqlite3 "$dbPath" "SELECT * FROM access WHERE service='kTCCServiceScreenCapture';"
+                execute_sql_query "$value" "$dbPath"
+                echo "Updated permissions for $dbPath"
+                echo "-------------------"
+                sudo sqlite3 "$dbPath" "SELECT * FROM access WHERE service='kTCCServiceScreenCapture';"
+              done
+            done
+  
+        - name: Run tests
+          id: test
+          timeout-minutes: 10
+          working-directory:
+            /opt/local/var/macports/build/_Users_runner_work_Sunshine_Sunshine_ports_multimedia_Sunshine/Sunshine/work/build/tests
+          run: |
+            sudo port install \
+              doxygen \
+              graphviz
+            sudo ./test_sunshine --gtest_color=yes
+  
+        - name: Generate gcov report
+          # any except canceled or skipped
+          if: always() && (steps.test.outcome == 'success' || steps.test.outcome == 'failure')
+          id: test_report
+          working-directory:
+            /opt/local/var/macports/build/_Users_runner_work_Sunshine_Sunshine_ports_multimedia_Sunshine/Sunshine/work
+          run: |
+            base_dir=$(pwd)
+            build_dir=${base_dir}/build
+  
+            # get the directory name that starts with Sunshine-*
+            dir=$(ls -d Sunshine-*)
+  
+            cd ${build_dir}
+            ${{ steps.python.outputs.python-path }} -m pip install gcovr
+            sudo ${{ steps.python.outputs.python-path }} -m gcovr -r ../${dir} \
+              --exclude-noncode-lines \
+              --exclude-throw-branches \
+              --exclude-unreachable-branches \
+              --exclude '.*${dir}/tests/.*' \
+              --exclude '.*${dir}/third-party/.*' \
+              --gcov-object-directory $(pwd) \
+              --verbose \
+              --xml-pretty \
+              -o ${{ github.workspace }}/build/coverage.xml
+  
+        - name: Upload coverage
+          # any except canceled or skipped
+          if: >-
+            always() &&
+            (steps.test_report.outcome == 'success') &&
+            startsWith(github.repository, 'LizardByte/')
+          uses: codecov/codecov-action@v4
+          with:
+            disable_search: true
+            fail_ci_if_error: false  # todo: re-enable this when action is fixed
+            files: ./build/coverage.xml
+            flags: ${{ runner.os }}-${{ matrix.os_version }}
+            token: ${{ secrets.CODECOV_TOKEN }}
+            verbose: true
+  
+        - name: Create/Update GitHub Release
+          if: ${{ needs.setup_release.outputs.publish_release == 'true' }}
+          uses: LizardByte/create-release-action@v2024.614.221009
+          with:
+            allowUpdates: true
+            body: ${{ needs.setup_release.outputs.release_body }}
+            discussionCategory: announcements
+            generateReleaseNotes: ${{ needs.setup_release.outputs.release_generate_release_notes }}
+            name: ${{ needs.setup_release.outputs.release_tag }}
+            prerelease: true
+            tag: ${{ needs.setup_release.outputs.release_tag }}
+            token: ${{ secrets.GH_BOT_TOKEN }}
+  
+    build_win:
+      name: Windows
+      runs-on: windows-2019
+      needs: [setup_release]
+  
+      steps:
+        - name: Checkout
+          uses: actions/checkout@v4
+          with:
+            submodules: recursive
+  
+        - name: Prepare tests
+          id: prepare-tests
+          if: false  # todo: DirectX11 is not available, so even software encoder fails
+          run: |
+            # function to download and extract a zip file
+            function DownloadAndExtract {
+              param (
+                [string]$Uri,
+                [string]$OutFile
+              )
+  
+              $maxRetries = 5
+              $retryCount = 0
+              $success = $false
+  
+              while (-not $success -and $retryCount -lt $maxRetries) {
+                $retryCount++
+                Write-Host "Downloading $Uri to $OutFile, attempt $retryCount of $maxRetries"
+                try {
+                  Invoke-WebRequest -Uri $Uri -OutFile $OutFile
+                  $success = $true
+                } catch {
+                  Write-Host "Attempt $retryCount of $maxRetries failed with error: $($_.Exception.Message). Retrying..."
+                  Start-Sleep -Seconds 5
+                }
               }
+  
+              if (-not $success) {
+                Write-Host "Failed to download the file after $maxRetries attempts."
+                exit 1
+              }
+  
+              # use .NET to get the base name of the file
+              $baseName = (Get-Item $OutFile).BaseName
+  
+              # Extract the zip file
+              Expand-Archive -Path $OutFile -DestinationPath $baseName
             }
 
             if (-not $success) {
